version: '3.8'

services:
  certification-authority:
    build:
      context: ./certification-authority-next
      dockerfile: ../Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres.djwfwgeikjfvyyksbqcz:WC35wleDddoBj7lJ@aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true
      - DIRECT_URL=postgresql://postgres.djwfwgeikjfvyyksbqcz:WC35wleDddoBj7lJ@aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
      - JWT_SECRET=${JWT_SECRET}
      - CA_CODE=${CA_CODE}
      - CA_PRIVATE_KEY=${CA_PRIVATE_KEY}
      - CA_PUBLIC_KEY=${CA_PUBLIC_KEY}
    volumes:
      - ./certification-authority-next/logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped

  information-provider:
    build:
      context: ./information-provider-next
      dockerfile: ../Dockerfile.information-provider
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres.djwfwgeikjfvyyksbqcz:WC35wleDddoBj7lJ@aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true
      - DIRECT_URL=postgresql://postgres.djwfwgeikjfvyyksbqcz:WC35wleDddoBj7lJ@aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
      - JWT_SECRET=${JWT_SECRET}
      - ANYA_BANK_API=${ANYA_BANK_API}
      - ANYA_CLIENT_ID=${ANYA_CLIENT_ID}
      - ANYA_CLIENT_SECRET=${ANYA_CLIENT_SECRET}
      - BOND_BANK_API=${BOND_BANK_API}
      - BOND_ORG_CODE=${BOND_ORG_CODE}
      - BOND_ORG_SERIAL_CODE=${BOND_ORG_SERIAL_CODE}
    volumes:
      - ./information-provider-next/logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    depends_on:
      - certification-authority

  mydata-operator:
    build:
      context: ./mydata-operator-next
      dockerfile: ../Dockerfile
    ports:
      - '4200:4200'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres.djwfwgeikjfvyyksbqcz:WC35wleDddoBj7lJ@aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres?pgbouncer=true
      - DIRECT_URL=postgresql://postgres.djwfwgeikjfvyyksbqcz:WC35wleDddoBj7lJ@aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
      - JWT_SECRET=${JWT_SECRET}
      - ANYA_BANK_API=${ANYA_BANK_API}
      - ANYA_CLIENT_ID=${ANYA_CLIENT_ID}
      - ANYA_CLIENT_SECRET=${ANYA_CLIENT_SECRET}
      - BOND_BANK_API=${BOND_BANK_API}
      - BOND_ORG_CODE=${BOND_ORG_CODE}
      - BOND_ORG_SERIAL_CODE=${BOND_ORG_SERIAL_CODE}
    volumes:
      - ./mydata-operator-next/logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    depends_on:
      - certification-authority
      - information-provider
