version: '3.8'

services:
  # Using Supabase instead of local Postgres
  # Commented out local postgres service as we're using Supabase
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: mydata-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: mydata
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - mydata-network

  redis:
    image: redis:alpine
    container_name: mydata-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - mydata-network

  certification-authority:
    build:
      context: ./certification-authority-next
      dockerfile: Dockerfile
    container_name: certification-authority
    restart: always
    depends_on:
      - redis
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      CA_API_URL: http://certification-authority:3000
      JWT_SECRET: starlight-anya-jwt-secret
      CA_CODE: certauth00
      CA_PRIVATE_KEY: certification-authority-private-key
      CA_PUBLIC_KEY: certification-authority-public-key
      BOND_BANK_API: http://mydata-operator:4200
      BOND_ORG_CODE: bond123456
      BOND_ORG_SERIAL_CODE: bondserial00
      BOND_CLIENT_ID: xv9gqz7mb4t2o5wcf8rjy6kphudsnea0l3ytkpdhqrvcxz1578
      BOND_CLIENT_SECRET: m4q7xv9zb2tgc8rjy6kphudsnea0l3ow5ytkpdhqrvcfz926bt
      ANYA_BANK_API: http://information-provider:4000
      ANYA_ORG_CODE: anya123456
      ANYA_ORG_SERIAL_CODE: anyaserial00
      ANYA_CLIENT_ID: wcf8rjy6kphudsnea0l3ytkpdhqrvcxz1578m4q7xv9zb2tgca
      ANYA_CLIENT_SECRET: a0l3ytkpdhqrvcfz926btm4q7xv9zb2tgc8rjy6kphudsnew5o
      NEXT_PUBLIC_CA_CODE: certauth00
      NEXT_PUBLIC_CA_PRIVATE_KEY: certification-authority-private-key
      NEXT_PUBLIC_CA_PUBLIC_KEY: certification-authority-public-key
      NEXT_PUBLIC_BOND_BANK_API: http://localhost:4200
      NEXT_PUBLIC_BOND_ORG_CODE: bond123456
      NEXT_PUBLIC_BOND_ORG_SERIAL_CODE: bondserial00
      NEXT_PUBLIC_BOND_CLIENT_ID: xv9gqz7mb4t2o5wcf8rjy6kphudsnea0l3ytkpdhqrvcxz1578
      NEXT_PUBLIC_BOND_CLIENT_SECRET: m4q7xv9zb2tgc8rjy6kphudsnea0l3ow5ytkpdhqrvcfz926bt
      NEXT_PUBLIC_ANYA_BANK_API: http://localhost:4000
      NEXT_PUBLIC_ANYA_ORG_CODE: anya123456
      NEXT_PUBLIC_ANYA_ORG_SERIAL_CODE: anyaserial00
      NEXT_PUBLIC_ANYA_CLIENT_ID: wcf8rjy6kphudsnea0l3ytkpdhqrvcxz1578m4q7xv9zb2tgca
      NEXT_PUBLIC_ANYA_CLIENT_SECRET: a0l3ytkpdhqrvcfz926btm4q7xv9zb2tgc8rjy6kphudsnew5o
    ports:
      - '3000:3000'
    networks:
      - mydata-network

  information-provider:
    build:
      context: ./information-provider-next
      dockerfile: Dockerfile
    container_name: information-provider
    restart: always
    depends_on:
      - redis
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      CA_API_URL: http://certification-authority:3000
      JWT_SECRET: starlight-anya-jwt-secret
      BOND_BANK_API: http://mydata-operator:4200
      BOND_ORG_CODE: bond123456
      ANYA_BANK_API: http://information-provider:4000
      ANYA_ORG_CODE: anya123456
      CA_CODE: certauth00
      ANYA_SERIAL_CODE: anyaserial00
      ANYA_CLIENT_ID: wcf8rjy6kphudsnea0l3ytkpdhqrvcxz1578m4q7xv9zb2tgca
      ANYA_CLIENT_SECRET: a0l3ytkpdhqrvcfz926btm4q7xv9zb2tgc8rjy6kphudsnew5o
      NEXT_PUBLIC_ANYA_CLIENT_ID: wcf8rjy6kphudsnea0l3ytkpdhqrvcxz1578m4q7xv9zb2tgca
      NEXT_PUBLIC_ANYA_CLIENT_SECRET: a0l3ytkpdhqrvcfz926btm4q7xv9zb2tgc8rjy6kphudsnew5o
      NEXT_PUBLIC_ANYA_ORG_NAME: Anya Bank
      NEXT_PUBLIC_ANYA_SERIAL_CODE: anyaserial00
      NEXT_PUBLIC_ANYA_ORG_CODE: anya123456
    ports:
      - '4000:4000'
    networks:
      - mydata-network

  mydata-operator:
    build:
      context: ./mydata-operator-next
      dockerfile: Dockerfile
    container_name: mydata-operator
    restart: always
    depends_on:
      - redis
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      CA_API_URL: http://certification-authority:3000
      JWT_SECRET: starlight-anya-jwt-secret
      ANYA_BANK_API: http://information-provider:4000
      ANYA_ORG_CODE: anya123456
      BOND_BANK_API: http://mydata-operator:4200
      BOND_ORG_CODE: bond123456
      BOND_CLIENT_ID: xv9gqz7mb4t2o5wcf8rjy6kphudsnea0l3ytkpdhqrvcxz1578
      BOND_CLIENT_SECRET: m4q7xv9zb2tgc8rjy6kphudsnea0l3ow5ytkpdhqrvcfz926bt
      CA_CODE: certauth00
      BOND_ORG_SERIAL_CODE: bondserial00
      NEXT_PUBLIC_BOND_CLIENT_ID: xv9gqz7mb4t2o5wcf8rjy6kphudsnea0l3ytkpdhqrvcxz1578
      NEXT_PUBLIC_BOND_CLIENT_SECRET: m4q7xv9zb2tgc8rjy6kphudsnea0l3ow5ytkpdhqrvcfz926bt
      NEXT_PUBLIC_BOND_ORG_NAME: Bond Bank
      NEXT_PUBLIC_BOND_ORG_CODE: bond123456
      NEXT_PUBLIC_BOND_SERIAL_CODE: bondserial00
    ports:
      - '4200:4200'
    networks:
      - mydata-network

networks:
  mydata-network:
    driver: bridge

volumes:
  redis-data:
