version: '3.8'

services:
  # Using Supabase instead of local Postgres
  # Commented out local postgres service as we're using Supabase
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: mydata-postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: mydata
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data n

  #   networks:
  #     - mydata-network

  certification-authority:
    build:
      context: ./certification-authority-next
      dockerfile: Dockerfile
    container_name: certification-authority
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
    ports:
      - '3000:3000'
    networks:
      mydata-network:
        aliases:
          - certification-authority

  information-provider:
    build:
      context: ./information-provider-next
      dockerfile: Dockerfile
    container_name: information-provider
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
    ports:
      - '4000:4000'
    networks:
      mydata-network:
        aliases:
          - information-provider

  mydata-operator:
    build:
      context: ./mydata-operator-next
      dockerfile: Dockerfile
    container_name: mydata-operator
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
    ports:
      - '4200:4200'
    networks:
      mydata-network:
        aliases:
          - mydata-operator

networks:
  mydata-network:
    name: mydata-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mydata-network
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
